version: '3.6'
services:
  weather:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/api
  db:
    image: mysql:5.7
    ports: 
    - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

